### PR TITLE
fix: add context parameter to example CLI tool

### PR DESCRIPTION
**Pull request by sagikazarmark**
Fixes regression introduced in #39

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Breaking CI seems to be unrelated (missing sonar config). Build seem to be fixed.

Any chance you could tag another release after merging this @thmeitz ?

**Comment by thmeitz** [comment]
ups didnt see your PR and fixed the cobra-example by myself.

Anyway, thank you four PR!

**Comment by thmeitz** [comment]
Yes there is a problem with sonar. Have to fix that!
All checks are ok, so I'll releasing v0.1.0. Have to write some things into the Readme about this breaking change...

**Comment by sagikazarmark** [comment]
No worries, thanks.

I'd suggest using GH's release feature and mentioning the BC break there.

**Pull request closed without merging**
